[package]
name = "dotenv_writer"
version = "0.1.0"
authors = ["Andreas Georgiou <me@ageorgiou.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
