[api]
dashboard = false
# insecure=true

[providers.docker]
exposedByDefault = false

[entryPoints]
  [entryPoints.web]
  address = ":80"

  [entryPoints.websecure]
  address = ":443"
  [entryPoints.websecure.http.tls]
  certResolver = "le"

[certificatesResolvers.le.acme]
email = "<traefik-email>"
storage = "/acme.json"
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.le.acme.httpChallenge]
  entryPoint = "web"
