[api]
dashboard = false
# insecure=true

[providers.docker]
exposedByDefault = false

  [entryPoints.web]
  address = ":80"

  [entryPoints.websecure]
  address = ":443"
  [entryPoints.websecure.http.tls]
  certResolver = "le"

  [certificatesResolvers.le.acme]
  email = "<traefik-email>"
  storage = "/acme.json"   
    [certificatesResolvers.le.acme.httpChallenge]
    entryPoint = "web"
