- Apps:
    - Owncloud:
        icon: owncloud
        href: https://owncloud.ageorgiou.com/
        description: Private and secure storage for your files
        server: my-docker
        container: owncloud_server

    - Jellyfin:
        icon: jellyfin
        href: http://jellyfin.home/
        description: Watch movies on-demand
        server: my-docker
        container: jellyfin

    - Pihole:
        icon: pi-hole
        href: http://pihole.home/
        description: Network-wide ad-blocking service
        server: my-docker
        container: pihole

    - Glances:
        icon: glances
        href: http://glances.home/
        description: A quick glance at the system's health and performance
        server: my-docker
        container: glances
